name: Github Actions AnxietyAlly
on: [push]
jobs:
  runAppAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "It's working"
      - uses: actions/checkout@v4
      - run: npm ci